/**
 * Getting list of yandex languages to codes
 * @returns yandex languages
 */
function yandexLanguages() {
  return {
    Russian: 'ru-RU',
    English: 'en-US',
    Turkish: 'tr-TR',
    Ukrainian: 'uk-UK',
  }
}

/**
 * Getting a list of available languages at Google
 * @returns object of all available languages at Google
 */
function googleLanguages() {
  return {
    'Afrikaans (South Africa)': 'af-ZA',
    'Amharic (Ethiopia)': 'am-ET',
    'Armenian (Armenia)': 'hy-AM',
    'Azerbaijani (Azerbaijan)': 'az-AZ',
    'Indonesian (Indonesia)': 'id-ID',
    'Malay (Malaysia)': 'ms-MY',
    'Bengali (Bangladesh)': 'bn-BD',
    'Bengali (India)': 'bn-IN',
    'Catalan (Spain)': 'ca-ES',
    'Czech (Czech Republic)': 'cs-CZ',
    'Danish (Denmark)': 'da-DK',
    'German (Germany)': 'de-DE',
    'English (Australia)': 'en-AU',
    'English (Canada)': 'en-CA',
    'English (Ghana)': 'en-GH',
    'English (United Kingdom)': 'en-GB',
    'English (India)': 'en-IN',
    'English (Ireland)': 'en-IE',
    'English (Kenya)': 'en-KE',
    'English (New Zealand)': 'en-NZ',
    'English (Nigeria)': 'en-NG',
    'English (Philippines)': 'en-PH',
    'English (South Africa)': 'en-ZA',
    'English (Tanzania)': 'en-TZ',
    'English (United States)': 'en-US',
    'Spanish (Argentina)': 'es-AR',
    'Spanish (Bolivia)': 'es-BO',
    'Spanish (Chile)': 'es-CL',
    'Spanish (Colombia)': 'es-CO',
    'Spanish (Costa Rica)': 'es-CR',
    'Spanish (Ecuador)': 'es-EC',
    'Spanish (El Salvador)': 'es-SV',
    'Spanish (Spain)': 'es-ES',
    'Spanish (United States)': 'es-US',
    'Spanish (Guatemala)': 'es-GT',
    'Spanish (Honduras)': 'es-HN',
    'Spanish (Mexico)': 'es-MX',
    'Spanish (Nicaragua)': 'es-NI',
    'Spanish (Panama)': 'es-PA',
    'Spanish (Paraguay)': 'es-PY',
    'Spanish (Peru)': 'es-PE',
    'Spanish (Puerto Rico)': 'es-PR',
    'Spanish (Dominican Republic)': 'es-DO',
    'Spanish (Uruguay)': 'es-UY',
    'Spanish (Venezuela)': 'es-VE',
    'Basque (Spain)': 'eu-ES',
    'Filipino (Philippines)': 'fil-PH',
    'French (Canada)': 'fr-CA',
    'French (France)': 'fr-FR',
    'Galician (Spain)': 'gl-ES',
    'Georgian (Georgia)': 'ka-GE',
    'Gujarati (India)': 'gu-IN',
    'Croatian (Croatia)': 'hr-HR',
    'Zulu (South Africa)': 'zu-ZA',
    'Icelandic (Iceland)': 'is-IS',
    'Italian (Italy)': 'it-IT',
    'Javanese (Indonesia)': 'jv-ID',
    'Kannada (India)': 'kn-IN',
    'Khmer (Cambodia)': 'km-KH',
    'Lao (Laos)': 'lo-LA',
    'Latvian (Latvia)': 'lv-LV',
    'Lithuanian (Lithuania)': 'lt-LT',
    'Hungarian (Hungary)': 'hu-HU',
    'Malayalam (India)': 'ml-IN',
    'Marathi (India)': 'mr-IN',
    'Dutch (Netherlands)': 'nl-NL',
    'Nepali (Nepal)': 'ne-NP',
    'Norwegian Bokmål (Norway)': 'nb-NO',
    'Polish (Poland)': 'pl-PL',
    'Portuguese (Brazil)': 'pt-BR',
    'Portuguese (Portugal)': 'pt-PT',
    'Romanian (Romania)': 'ro-RO',
    'Sinhala (Sri Lanka)': 'si-LK',
    'Slovak (Slovakia)': 'sk-SK',
    'Slovenian (Slovenia)': 'sl-SI',
    'Sundanese (Indonesia)': 'su-ID',
    'Swahili (Tanzania)': 'sw-TZ',
    'Swahili (Kenya)': 'sw-KE',
    'Finnish (Finland)': 'fi-FI',
    'Swedish (Sweden)': 'sv-SE',
    'Tamil (India)': 'ta-IN',
    'Tamil (Singapore)': 'ta-SG',
    'Tamil (Sri Lanka)': 'ta-LK',
    'Tamil (Malaysia)': 'ta-MY',
    'Telugu (India)': 'te-IN',
    'Vietnamese (Vietnam)': 'vi-VN',
    'Turkish (Turkey)': 'tr-TR',
    'Urdu (Pakistan)': 'ur-PK',
    'Urdu (India)': 'ur-IN',
    'Greek (Greece)': 'el-GR',
    'Bulgarian (Bulgaria)': 'bg-BG',
    'Russian (Russia)': 'ru-RU',
    'Serbian (Serbia)': 'sr-RS',
    'Ukrainian (Ukraine)': 'uk-UA',
    'Hebrew (Israel)': 'he-IL',
    'Arabic (Israel)': 'ar-IL',
    'Arabic (Jordan)': 'ar-JO',
    'Arabic (United Arab Emirates)': 'ar-AE',
    'Arabic (Bahrain)': 'ar-BH',
    'Arabic (Algeria)': 'ar-DZ',
    'Arabic (Saudi Arabia)': 'ar-SA',
    'Arabic (Iraq)': 'ar-IQ',
    'Arabic (Kuwait)': 'ar-KW',
    'Arabic (Morocco)': 'ar-MA',
    'Arabic (Tunisia)': 'ar-TN',
    'Arabic (Oman)': 'ar-OM',
    'Arabic (State of Palestine)': 'ar-PS',
    'Arabic (Qatar)': 'ar-QA',
    'Arabic (Lebanon)': 'ar-LB',
    'Arabic (Egypt)': 'ar-EG',
    'Persian (Iran)': 'fa-IR',
    'Hindi (India)': 'hi-IN',
    'Thai (Thailand)': 'th-TH',
    'Korean (South Korea)': 'ko-KR',
    'Chinese, Mandarin (Traditional, Taiwan)': 'cmn-Hant-TW',
    'Chinese, Cantonese (Traditional, Hong Kong)': 'yue-Hant-HK',
    'Japanese (Japan)': 'ja-JP',
    'Chinese, Mandarin (Simplified, Hong Kong)': 'cmn-Hans-HK',
    'Chinese, Mandarin (Simplified, China)': 'cmn-Hans-CN',
  }
}

/**
 * Getting a list of wit languages
 * @returns wit languages
 */
function witLanguages() {
  return JSON.parse(process.env.WIT_LANGUAGES)
}

/**
 * Getting available wit codes
 * @returns available wit codes
 */
function witCodes() {
  return {
    af: 'Afrikaans',
    sq: 'Albanian',
    ar: 'Arabic',
    az: 'Azerbaijani',
    bn: 'Bengali',
    bs: 'Bosnian',
    bg: 'Bulgarian',
    my: 'Burmese',
    ca: 'Catalan',
    km: 'Central Khmer',
    zh: 'Chinese',
    hr: 'Croatian',
    cs: 'Czech',
    da: 'Danish',
    nl: 'Dutch',
    en: 'English',
    et: 'Estonian',
    fi: 'Finnish',
    fr: 'French',
    ka: 'Georgian',
    de: 'German',
    el: 'Greek',
    kl: 'Greenlandic',
    ha: 'Hausa',
    he: 'Hebrew',
    hi: 'Hindi',
    hu: 'Hungarian',
    is: 'Icelandic',
    ig: 'Igbo',
    id: 'Indonesian',
    iu: 'Inuktitut',
    it: 'Italian',
    ja: 'Japanese',
    kn: 'Kannada',
    rw: 'Kinyarwanda',
    ko: 'Korean',
    lo: 'Lao',
    la: 'Latin',
    lt: 'Lithuanian',
    mk: 'Macedonian',
    ms: 'Malay',
    mi: 'Maori',
    mn: 'Mongolian',
    ne: 'Nepali',
    no: 'Norwegian',
    ps: 'Pashto',
    fa: 'Persian',
    pl: 'Polish',
    pt: 'Portugese',
    ro: 'Romanian',
    ru: 'Russian',
    sr: 'Serbian',
    sk: 'Slovak',
    sl: 'Slovenian',
    so: 'Somali',
    nr: 'Southern Ndebele',
    st: 'Southern Sotho',
    es: 'Spanish',
    sw: 'Swahili',
    ss: 'Swati',
    sv: 'Swedish',
    tl: 'Tagalog',
    ta: 'Tamil',
    te: 'Telugu',
    th: 'Thai',
    ts: 'Tsonga',
    tn: 'Tswana',
    tr: 'Turkish',
    uk: 'Ukrainian',
    ur: 'Urdu',
    uz: 'Uzbek',
    ve: 'Venda',
    vi: 'Vietnamese',
    xh: 'Xhosa',
    yo: 'Yoruba',
    zu: 'Zulu',
  }
}

// Exports
module.exports = {
  yandexLanguages,
  googleLanguages,
  witLanguages,
  witCodes,
}
